# Este archivo sirve para crear registros de prueba
Task.create(name:"Programar", status:false)
Task.create(name:"Comer", status:false)
Task.create(name:"Caminar", status:false)
Task.create(name:"Correr", status:false)
Task.create(name:"Ejercicio", status:false)
Task.create(name:"Cocinar", status:false)
Task.create(name:"Aplicacion", status:false)
Task.create(name:"Pagina", status:false)
Task.create(name:"Estudiar", status:false)
Task.create(name:"Leer", status:false)
Task.create(name:"Nadar", status:false)
Task.create(name:"Viajar", status:false)
Task.create(name:"Manejar", status:false)
Task.create(name:"Dibujar", status:false)
Task.create(name:"Pintar", status:false)